### ISSUE TITLE
Add support for missing types in inferrers

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#129]
There are some PG-specific types that we should add to [pg inferrer](https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/extensions/postgres/inferrer.rb). This is especially important for hanami-model where it's not possible to define attributes manually (at least not yet), so **this is a blocker for hanami-model 1.0.0**.

### TODO

Specs should go to `spec/integration/schema/inferrer/#{db_type}_spec`, we have a bunch of specs already for common stuff, if there's anything db-specific in existing specs, it should be moved to a new spec that's dedicated to a given db engine.

- [x] Add `Types::PG::IPAddress` (this can be a `Types::String` for a good start)
- [x] Add `Types::PG::GeoPoint` (I'm not exactly sure what this should be :))
- [x] Add `Inferrer[:mysql]`
- [x] Add `Inferrer[:sqlite]`
- [x] Extend PG inferrer with a mapping `"inet" => Types::PG::IPAddress`
- [x] Extend PG inferrer with a mapping `"point" => Types::PG::GeoPoint`
- [x] Extend inferrers with a mapping `"numeric(precision)" => Types::Float.meta(precision: precision)` (I think?)
- [x] Extend inferrers with a mapping `"decimal(precision)" => Types::Decimal.meta(precision: precision`
- [x] Extend inferrers with a mapping `"decimal(precision, scale)" => Types::Decimal.meta(precision: precision, scale: scale)`
- [ ] Figure out which numeric/decimal db types are common for sqlite/mysql/postgres, ie from what I've seen `numeric(precision)` is used by Sequel in all 3 dbs

/cc @flash-gordon @jodosha

**Comment by jodosha** [comment]
@solnic Thanks for defining all the missing steps. 👍
